// import adidas from '/brand/adidas.png'
// import arvato from '/brand/arvato.png'
// import ceva from '/brand/ceva.png'
// import dhl from '/brand/dhl.png'
// import eberspacher from '/brand/eberspacher.png'
// import geodis from '/brand/geodis.png'
// import geodis2 from '/brand/geodis2.png'
// import jd from '/brand/jd.png'
// import mahle from '/brand/mahle.png'
// import mcmaster from '/brands/mcmaster.png'
// import skoda from '/brand/skoda.png'
// import toyota from '/brand/toyota.png'
// import vw from '/brand/vw.png'
// import zalando from '/brand/zalando.png'

